In [13]:
import numpy as np

With NumPy, we can add entire arrays with a single operation, while Python lists require a loop to do the same thing. For small arrays, the difference might not be noticeable. But for large arrays with thousands or millions of elements, NumPy can be hundreds of times faster.


In [11]:
list1 = [1, 2, 3, 4, 5]
list2 = [6, 7, 8, 9, 10]
result = []
for i in range(len(list1)):
    result.append(list1[i] + list2[i])

result

[7, 9, 11, 13, 15]

In [12]:
array1 = np.array([1, 2, 3, 4, 5])
array2 = np.array([6, 7, 8, 9, 10])
result = array1 + array2
result

array([ 7,  9, 11, 13, 15])

In NumPy, axes are the directions along which operations are performed. They correspond to the dimensions of an array, starting with axis=0 for the outermost dimension.

As dimensions increase, the axis number refers to the level of nesting in the array:
Axis 0: The outermost level (e.g., separate matrices or "planes").
Axis 1: The next level in (e.g., rows within each matrix).
Axis 2: The next level in (e.g., columns within each row).
Axis -1: The very last dimension, regardless of how many there are.

In [27]:
a = np.array([[
    [1, 2, 3],
    [4, 5, 6]
],
             [
    [7, 8, 9],
    [10, 11, 12]         
]]
)
print(a.shape)
print(a.sum(axis=2))

(2, 2, 3)
[[ 6 15]
 [24 33]]


Basic Slicing Syntax

The basic syntax is array[start:end:step], where:

start is where to begin (inclusive)
end is where to stop (exclusive)
step is how many items to skip (default is 1)

In [37]:
# 2D Array Slicing
arr = np.array([
    [1, 2, 3], 
    [4, 5, 6],
    [7, 8, 9]
])

arr[0:2, 1:3]

array([[2, 3],
       [5, 6]])

In [38]:
# 3D Array Slicing
arr1 = np.array([
    [
        [1, 2, 3],
        [4, 5, 6]
    ],
    [
        [7, 8, 9],
        [10, 11, 12]
    ],
    [
        [13, 14, 15],
        [16, 17, 18]
    ]
])

arr1[1:, 1:, :]

array([[[10, 11, 12]],

       [[16, 17, 18]]])

Advanced Slicing Techniques

In [39]:
# Boolean Indexing

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
evens = arr[arr % 2 == 0]
evens

array([ 2,  4,  6,  8, 10])

In [43]:
# Fancy Indexing

selected = arr[[1, 3, 5, 7, 9]]
selected

array([ 2,  4,  6,  8, 10])

Concept of View and Copy in NumPy

view_arr points to the same data in memory as arr.

Copy : A copy is like making a photocopy of the data. It’s a completely new array with its own data.

In [ ]:
arr = np.array([1, 2, 3, 4])
view_arr = arr[1:3] # view not a copy

view_arr[0] = 99
print(arr)  

[ 1 99  3  4]


In [ ]:
arr = np.array([1, 2, 3, 4])
view_arr = arr[:] # view not a copy

view_arr[0] = 99
print(arr)

[99  2  3  4]


In [46]:
arr = np.array([10, 20, 30, 40])
copy_arr = arr[1:3].copy() # copy not a view
copy_arr[0] = 99
print(arr)

[10 20 30 40]


Creating Arrays Easily with NumPy’s Built-in Methods

In [ ]:
a = np.zeros((2, 3))
a

array([[0., 0., 0.],
       [0., 0., 0.]])

In [48]:
b = np.ones((3, 2))
print(b)

[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [49]:
c = np.full((2, 3), 7)
print(c)

[[7 7 7]
 [7 7 7]]


In [52]:
d = np.arange(2, 11, 2)
print(d)

e = np.arange(11)
print(e)

[ 2  4  6  8 10]
[ 0  1  2  3  4  5  6  7  8  9 10]


In [55]:
f = np.linspace(0, 10, 5)
print(f)
g = np.linspace(0, 10, 9)
print(g)

[ 0.   2.5  5.   7.5 10. ]
[ 0.    1.25  2.5   3.75  5.    6.25  7.5   8.75 10.  ]


In [57]:
h = np.eye(3) # Creates an identity matrix
h

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [58]:
i = np.random.random((2, 2))
print(i)

[[0.74192525 0.36435589]
 [0.7743255  0.25172496]]


Reshaping Array

One of NumPy’s superpowers is changing the shape of an array without changing its data. 

In [59]:
arr = np.arange(6)
print(arr)

reshaped_arr = arr.reshape((2, 3))
print(reshaped_arr)

[0 1 2 3 4 5]
[[0 1 2]
 [3 4 5]]


In [62]:
print(reshaped_arr.flatten()) # Flattens the array to 1D

[0 1 2 3 4 5]


NumPy’s “broadcasting” feature is like a smart assistant that intelligently handles operations between arrays of different shapes.

In [65]:
grid = np.array([[1, 2, 3], [4, 5, 6]])

# Add 10 to every item in the grid
result = grid + 10
# The number 10 was "broadcast" or stretched to fit the shape of the grid.

result

array([[11, 12, 13],
       [14, 15, 16]])

In [67]:
grid = np.array([[1, 2, 3], [4, 5, 6]])
row = np.array([10, 20, 30])

# Add the 'row' to each row of the 'grid'
result = grid + row
result

array([[11, 22, 33],
       [14, 25, 36]])