# Numpy

*CSCI 115*

**Date:** 2026-04-17

---

## Learning goals

- Create NumPy arrays using `np.arange()`
- Reshape arrays and use broadcasting to perform operations without loops
- Slice 2D arrays, including reversing rows and columns
- Perform vectorized arithmetic on arrays
- Use `np.sum()`, `np.argmax()`, `np.argmin()`, `np.unique()`, and `np.where()`
- Use boolean indexing to filter array elements

---

## Task 1. Multiplication Table (broadcasting + reshape + slicing)

1. Import `numpy` with the standard alias `np`.
2. Create a 1D array `rows` containing values 1 through 10.
3. Reshape it into a column vector of shape `(10, 1)`.
4. Create another 1D array `cols` containing values 1 through 10 (shape `(10,)`).
5. Use broadcasting to multiply them and produce a 10×10 multiplication table. Store the result in a variable called `result`. No loops allowed!
   

In [8]:
import numpy as np

rows = np.arange(1, 11)
rows = rows.reshape(1, 10)
cols = np.arange(1, 11)
cols = cols.reshape(10, 1)
result = rows * cols
result

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [  2,   4,   6,   8,  10,  12,  14,  16,  18,  20],
       [  3,   6,   9,  12,  15,  18,  21,  24,  27,  30],
       [  4,   8,  12,  16,  20,  24,  28,  32,  36,  40],
       [  5,  10,  15,  20,  25,  30,  35,  40,  45,  50],
       [  6,  12,  18,  24,  30,  36,  42,  48,  54,  60],
       [  7,  14,  21,  28,  35,  42,  49,  56,  63,  70],
       [  8,  16,  24,  32,  40,  48,  56,  64,  72,  80],
       [  9,  18,  27,  36,  45,  54,  63,  72,  81,  90],
       [ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100]])

6. Once you have `rows`, `cols`, and `result`, run the cell below without any modification. If your code is correct, you will see a valid equation and a multiplication table.

In [9]:
from IPython.display import display, Math
import random

def to_latex(arr, highlight=False):
    n, m = np.atleast_2d(arr).shape
    if highlight:
        r1, c1 = random.randint(0, n-2), random.randint(0, m-2)
        r2, c2 = random.randint(r1+1, min(r1+5, n)), random.randint(c1+1, min(c1+5, m))
    lines = []
    for i, row in enumerate(np.atleast_2d(arr)):
        cells = [rf"\color{{#DC143C}}{{{v}}}" if highlight and r1<=i<r2 and c1<=j<c2 else str(v)
                 for j, v in enumerate(row)]
        lines.append(" & ".join(cells))
    return r"\begin{bmatrix}" + r"\\".join(lines) + r"\end{bmatrix}"

display(Math(to_latex(rows) + r"\times" + to_latex(cols) + "=" + to_latex(result, highlight=True)))


<IPython.core.display.Math object>

7. You should see a random subarray highlighted in red in the multiplication table above. Using slicing on `result`, extract exactly that subarray. Your output must match the highlighted values.

**Hint:** look at which rows and columns are highlighted and use `result[r1:r2, c1:c2]` with the correct indices.

In [12]:
print(result[4:7, 8:])


[[45 50]
 [54 60]
 [63 70]]


---

## Task 2. Dice Simulation (random + axis operations + unique + argmax)

A classic probability experiment: roll two dice thousands of times and analyze the results.

### 2.1 Roll the dice

1. Use `np.random.randint()` to simulate 10,000 rolls of two dice. The result should be a 2D array of shape `(10000, 2)`, where each row is one roll and the two columns represent the two dice.

   **Hint:** Use `help(np.random.randint)` to find out how to get the needed shape of the array.
   
3. Print the shape of the array and its first 5 rows.


In [20]:
random_arr = np.random.randint(1, 7, (10000, 2))
print(random_arr[:5])
print(random_arr.shape)

[[2 2]
 [6 6]
 [5 3]
 [2 6]
 [1 6]]
(10000, 2)


### 2.2 Compute the sums

3. Compute the sum of each roll (sum across columns) to get a 1D array of 10,000 sums. Use the `axis` parameter. Again, don't use any loops!
4. Print the shape of the resulting array and its first 10 values.

In [22]:
print(random_arr.shape)
print(random_arr.sum(axis=1)[:10])

(10000, 2)
[ 4 12  8  8  7  5  6  5 10  5]


### 2.3 Count each outcome

5. Use `np.unique()` with `return_counts=True` to find how many times each possible sum (2 through 12) appeared.
6. Print each sum and its count.

In [23]:
values, counts = np.unique(random_arr.sum(axis=1), return_counts=True)

for v, c in zip(values, counts):
    print("Sum", v, "->", c, "times")


Sum 2 -> 289 times
Sum 3 -> 548 times
Sum 4 -> 862 times
Sum 5 -> 1061 times
Sum 6 -> 1357 times
Sum 7 -> 1705 times
Sum 8 -> 1378 times
Sum 9 -> 1149 times
Sum 10 -> 833 times
Sum 11 -> 541 times
Sum 12 -> 277 times


### 2.4 Find the most common sum

7. Using `np.argmax()` on the counts array, find and print the most common sum and how many times it occurred.

Explain why this number is the most likely sum of two dice.


In [25]:
index = int(np.argmax(counts))

print(counts[index])
print(values[index])

1705
7


---

## Task 3. NU Pixel Art (2D arrays + slicing + vectorized arithmetic)

In this task, you will work with a 12×12 NumPy array that represents a simple image: the letters "NU" drawn with 1s and 0s. NumPy operates on numbers, but we will use a helper function `show()` to display the array as `#` (for 1) and `.` (for 0) so the image is easier to read.

### 3.1 Display the image

Run the cell below to create the array and display it. You should see the letters "NU".

In [26]:
# Run this cell. DO NOT MODIFY

import numpy as np

art = np.zeros((12, 12), dtype=int)

art[1:11, 0] = 1
art[1:11, 5] = 1
for i in range(10):
    row = 1 + i
    col = int(0.5 + i * 5 / 9)
    art[row, col] = 1

art[1:10, 7] = 1
art[1:10, 11] = 1
art[10, 8:11] = 1

def show(arr):
    """Display a 2D array of 0s and 1s as # and . characters."""
    for row in arr:
        print(" ".join(["#" if val else "." for val in row]))

show(art)


. . . . . . . . . . . .
# . . . . # . # . . . #
# # . . . # . # . . . #
# # . . . # . # . . . #
# . # . . # . # . . . #
# . # . . # . # . . . #
# . . # . # . # . . . #
# . . # . # . # . . . #
# . . . # # . # . . . #
# . . . # # . # . . . #
# . . . . # . . # # # .
. . . . . . . . . . . .


### 3.2 Flip horizontally

Create a horizontally flipped version of `art` using slicing: reverse the order of columns so the image appears mirrored. Display it using `show()`. No loops allowed!

**Hint:** To reverse columns, use `[:, ::-1]`.

In [33]:
show(art[:, ::-1])

. . . . . . . . . . . .
# . . . # . # . . . . #
# . . . # . # . . . # #
# . . . # . # . . . # #
# . . . # . # . . # . #
# . . . # . # . . # . #
# . . . # . # . # . . #
# . . . # . # . # . . #
# . . . # . # # . . . #
# . . . # . # # . . . #
. # # # . . # . . . . #
. . . . . . . . . . . .


### 3.3 Flip vertically

Create a vertically flipped (upside-down) version of `art` using slicing: reverse the order of rows. Display it using `show()`.

In [34]:
show(art[::-1, :])

. . . . . . . . . . . .
# . . . . # . . # # # .
# . . . # # . # . . . #
# . . . # # . # . . . #
# . . # . # . # . . . #
# . . # . # . # . . . #
# . # . . # . # . . . #
# . # . . # . # . . . #
# # . . . # . # . . . #
# # . . . # . # . . . #
# . . . . # . # . . . #
. . . . . . . . . . . .


### 3.4 Invert the image

Create an inverted ("dark mode") version of `art` where every 0 becomes 1 and every 1 becomes 0. Do this in a single expression using vectorized arithmetic. No loops, no `if` statements!

Display the result using `show()`.

**Hint:** Think about what arithmetic operation turns 0 into 1 and 1 into 0.

In [47]:
show(art^1)

# # # # # # # # # # # #
. # # # # . # . # # # .
. . # # # . # . # # # .
. . # # # . # . # # # .
. # . # # . # . # # # .
. # . # # . # . # # # .
. # # . # . # . # # # .
. # # . # . # . # # # .
. # # # . . # . # # # .
. # # # . . # . # # # .
. # # # # . # # . . . #
# # # # # # # # # # # #


In [60]:
show(1-art)

# # # # # # # # # # # #
. # # # # . # . # # # .
. . # # # . # . # # # .
. . # # # . # . # # # .
. # . # # . # . # # # .
. # . # # . # . # # # .
. # # . # . # . # # # .
. # # . # . # . # # # .
. # # # . . # . # # # .
. # # # . . # . # # # .
. # # # # . # # . . . #
# # # # # # # # # # # #


### 3.5 Count lit pixels

Using `np.sum()`, count and print how many pixels in the original `art` are "lit" (equal to 1).

In [48]:
print("Lit pixels:", np.sum(art==1))

Lit pixels: 49


---

## Task 4. Distance Between Cities (broadcasting + reshape + argmin)

You are given the coordinates (latitude and longitude) of 5 cities in Kazakhstan. Your goal is to compute the straight-line distance between every pair of cities using NumPy, without any loops.

The Euclidean distance between two points $(lat_1, lon_1)$ and $(lat_2, lon_2)$ is:

$$d = \sqrt{(lat_1 - lat_2)^2 + (lon_1 - lon_2)^2}$$

**Note:** This is a simplified distance using coordinates as plain numbers, not the real geographic distance. It is enough for comparison purposes.

### 4.1 Set up the data

Run the cell below to create the arrays. Do not modify this code.

In [49]:
# Run this cell. DO NOT MODIFY

names = ["Astana", "Almaty", "Shymkent", "Aktobe", "Karaganda"]
lat = np.array([51.17, 43.14, 42.19, 50.30, 49.80])
lon = np.array([71.43, 76.57, 69.35, 57.21, 73.10])


### 4.2 Build the distance matrix

Compute a 5×5 distance matrix where entry `[i, j]` is the distance between city `i` and city `j`. Use broadcasting, no loops allowed!

**Step-by-step guide:**

1. Reshape `lat` into a column vector of shape `(5, 1)`. Subtract the original `lat` of shape `(5,)` from it. Broadcasting will produce a `(5, 5)` matrix of latitude differences. Store it in `dlat`.

2. Do the same for `lon` → store in `dlon`.

3. Apply the distance formula: `dist = np.sqrt(dlat**2 + dlon**2)`.

4. Print the result using the `show_matrix()` function provided below.

**Hint:** This is the same broadcasting idea as Task 1: a column vector times (or minus) a row vector gives a 2D matrix.

In [50]:
# Run this cell. DO NOT MODIFY
# Helper function to display the distance matrix with city names

def show_matrix(matrix, names):
    header = "           " + "  ".join([f"{n:>10}" for n in names])
    print(header)
    for i in range(len(names)):
        row = f"{names[i]:>10} " + "  ".join([f"{matrix[i,j]:10.2f}" for j in range(len(names))])
        print(row)

In [52]:
dlat = lat.reshape(5, 1) - lat
dlon = lon.reshape(5, 1) - lon
dist = np.sqrt(dlat**2 + dlon**2)

show_matrix(dist, names)


               Astana      Almaty    Shymkent      Aktobe   Karaganda
    Astana       0.00        9.53        9.22       14.25        2.16
    Almaty       9.53        0.00        7.28       20.64        7.51
  Shymkent       9.22        7.28        0.00       14.60        8.48
    Aktobe      14.25       20.64       14.60        0.00       15.90
 Karaganda       2.16        7.51        8.48       15.90        0.00


### 4.3 Find the nearest neighbor

For each city, find which other city is closest to it.

**Step-by-step guide:**

1. First, set the diagonal of `dist` to `np.inf`. This prevents a city from being its own nearest neighbor. You can do this with: `dist[np.arange(5), np.arange(5)] = np.inf`

2. Use `np.argmin(dist, axis=1)` to find the index of the smallest value in each row.

3. Print the nearest neighbor for each city.

**Expected output:**

Astana -> Karaganda <br>
Almaty -> Shymkent <br>
Shymkent -> Almaty <br>
Aktobe -> Astana <br>
Karaganda -> Astana <br>


In [58]:
dist[np.arange(5), np.arange(5)] = np.inf
indexes = np.argmin(dist, axis=1)
for i in range(5):
    print(f"{names[i]} -> {names[indexes[i]]}")

Astana -> Karaganda
Almaty -> Shymkent
Shymkent -> Almaty
Aktobe -> Astana
Karaganda -> Astana


### 4.4 Find the farthest pair

Find the two cities that are farthest apart from each other.

**Step-by-step guide:**

1. Reset the diagonal back to 0: `dist[np.arange(5), np.arange(5)] = 0`

2. Find the maximum distance using `dist.max()`.

3. Use `np.where(dist == dist.max())` to find the row and column indices of that maximum value.

4. Print the names of the two cities and the distance between them.

In [59]:
dist[np.arange(5), np.arange(5)] = 0
indexes = np.argmax(dist, axis=1)
for i in range(5):
    print(f"{names[i]} -> {names[indexes[i]]}")

Astana -> Aktobe
Almaty -> Aktobe
Shymkent -> Aktobe
Aktobe -> Almaty
Karaganda -> Aktobe
